---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./src/*.js"
    - "./tests/*"
postMerge:
  pattern:
    - "./src/*.js"
    - "./tests/*"
postRun:
     command:
        - yarn --version
version: 1.0
